const students = [
  {
    id: 1,
    faculty: "Somesh Sharma",
    names: [
      "Savya Sharma",
      "Sandeep Sain",
      "Rupendra Choudhary",
      "Vishal Nayak",
      "Harshit Sharma",
      "Manish Lega",
      "Akash Kumar Sain",
      "Sonu Jangid",
      "Anuj Sharma",
      "Gajender Yadav",
      "Siddharth Jeenwal",
      "Anurag Bhuria",
      "Bhoomi Sharma",
      "Upender Swami",
      "Aviyansh",
      "Anand Swami",
      "Shrishti Sinha",
      "Prinjal",
      "Ankit Nihala",
      "Vikas Kumar Sain",
      "Nirbhya Saini",
      "Prakram Pachori",
      "Pankaj",
    ],
  },
  {
    id: 1,
    faculty: "Rohit Jain",
    names: [
      "Shashwat Soni",
      "Ashish Garg",
      "Muskan Pradhan",
      "Saksham Jain",
      "Prem Lalwani",
      "Shubh Gaur",
      "Shashank Goyal",
      "Sankalp Gupta",
      "Erfan Aalam",
      "Divyansh Sahu",
      "Ved Prakash",
      "Surbhi Singhal",
      "Ankita Priya",
      "Garvit Jangir",
      "Nihit Jangir",
      "Akshat Sharma",
      "Dheeraj Jangid",
      "Kartik Sharma",
      "Ranveer Singh",
      "Harendra Rana",
      "Sudhir Mishra",
      "Chandan Lakhara",
      "Priya",
      "Ashish Pancholi",
      "Himanshu Poonia"
    ],
  },
];

export default students